---
swagger: "2.0"
info:
  description: "API-Documentation for the 'kkl_ligatool' Wordpress-Plugin"
  version: "1.0.0"
  title: "Kickerliga KÃ¶ln"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "stephan@5711.org"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "www.kickerligakoeln.de"
basePath: "/wp-json/kkl/v1"
tags:
- name: "admins"
  description: "Everything about Admins"
- name: "clubs"
  description: "Everything about Clubs"
- name: "gamedays"
  description: "Everything about GameDays"
- name: "leagues"
  description: "Everything about Leagues"
- name: "locations"
  description: "Everything about Locations"
- name: "matches"
  description: "Everything about Matches"
- name: "players"
  description: "Everything about Players"
- name: "seasons"
  description: "Everything about Seasons"
- name: "teams"
  description: "Everything about Teams"
schemes:
- "https"
paths:
  /leagues:
    get:
      tags:
      - "leagues"
      summary: "Display all leagues in the tool"
      description: ""
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/League"
  /leagues/{leagueId}:
    get:
      tags:
      - "leagues"
      summary: "Find leagues by ID"
      description: "Returns a single league"
      produces:
      - "application/json"
      parameters:
      - name: "leagueId"
        in: "path"
        description: "ID of league to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/League"
        404:
          description: "League not found"
  /leagues/{leagueId}/properties:
    get:
      tags:
      - "leagues"
      summary: "Find properties for league"
      description: "Returns properties for league"
      produces:
      - "application/json"
      parameters:
      - name: "leagueId"
        in: "path"
        description: "ID of league to return properties for"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Property"
        404:
          description: "League not found"
  /leagues/{leagueId}/seasons:
    get:
      tags:
      - "leagues"
      summary: "Find seasons for league"
      description: "Returns a list for seasons for league leagues"
      produces:
      - "application/json"
      parameters:
      - name: "leagueId"
        in: "path"
        description: "ID of league to return properties for"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Season"
        404:
          description: "League not found"
  /leagues/{leagueId}/currentseason:
    get:
      tags:
      - "leagues"
      summary: "Find current season for league"
      description: "Returns the currently running season for the given league"
      produces:
      - "application/json"
      parameters:
      - name: "leagueId"
        in: "path"
        description: "ID of league to return properties for"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Season"
        404:
          description: "League not found"
definitions:
  League:
    properties:
      id:
        type: "integer"
        format: "int64"
      createdAt:
        type: "integer"
        format: "int64"
      updatedAt:
        type: "integer"
        format: "int32"
      active:
        type: "string"
        format: "date-time"
      code:
        type: "string"
        format: "date-time"
      name:
        type: "string"
        format: "date-time"
      currentSeason:
        type: "string"
        format: "date-time"
      _links:
        type: "string"
      _embedded:
        type: "boolean"
    example:
      createdAt: 6
      code: "2000-01-23T04:56:07.000+00:00"
      _links: "_links"
      _embedded: true
      currentSeason: "2000-01-23T04:56:07.000+00:00"
      name: "2000-01-23T04:56:07.000+00:00"
      active: "2000-01-23T04:56:07.000+00:00"
      id: 0
      updatedAt: 1
  Season:
    properties:
      id:
        type: "integer"
        format: "int64"
      createdAt:
        type: "integer"
        format: "int64"
      updatedAt:
        type: "integer"
        format: "int32"
      active:
        type: "string"
        format: "date-time"
      endDate:
        type: "string"
        format: "date-time"
      name:
        type: "string"
        format: "date-time"
      startDate:
        type: "string"
        format: "date-time"
      currentGameDay:
        type: "string"
        format: "date-time"
      leagueId:
        type: "string"
        format: "date-time"
      _links:
        type: "string"
      _embedded:
        type: "boolean"
    example:
      createdAt: 6
      currentGameDay: "2000-01-23T04:56:07.000+00:00"
      endDate: "2000-01-23T04:56:07.000+00:00"
      _links: "_links"
      _embedded: true
      leagueId: "2000-01-23T04:56:07.000+00:00"
      name: "2000-01-23T04:56:07.000+00:00"
      active: "2000-01-23T04:56:07.000+00:00"
      id: 0
      startDate: "2000-01-23T04:56:07.000+00:00"
      updatedAt: 1
  Property:
    properties:
      id:
        type: "integer"
        format: "int64"
      key:
        type: "string"
      value:
        type: "string"
    example:
      id: 0
      value: "value"
      key: "key"
    xml:
      name: "User"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
